version: '3.8'

services:
  web:
    image: hacking_server
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: hacking_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"